backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"       # Where uploaded files go in your repo
public_folder: "/uploads"             # How those files are accessed in your site

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
